# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/winter/blog/models/category/columns.yaml

# Model Class name
modelClass: Winter\Blog\Models\Category

# List Title
title: winter.blog::lang.category.label_plural

# Link URL for each record
recordUrl: winter/blog/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 5

# Display checkboxes next to each record
showCheckboxes: true

showTree: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



